"""
Basic context operations example.

This example demonstrates:
- Creating a session with context (read_write mode)
"""
from lexmount import Lexmount, ContextNotFoundError, set_log_level
from dotenv import load_dotenv
from pathlib import Path
import argparse
import sys

load_dotenv(override=True)

# Set logging to DEBUG to see detailed request/response
set_log_level("DEBUG")

client = Lexmount()

def main():
    """Demonstrate basic context operations."""
    parser = argparse.ArgumentParser(description="Context management basic operations")
    parser.add_argument("--context-id", help="Use this context ID directly; if omitted, create a new context")
    args = parser.parse_args()

    print("=" * 60)
    print("Context Management - Basic Operations")
    print("=" * 60)

    try:
        if args.context_id:
            context_id = args.context_id
            print(f"\n1. Using existing context ID: {context_id}")
        else:
            # Create a new context (ID generated by server)
            print("\n1. Creating a new context...")
            context = client.contexts.create(
                metadata={
                    "user": "demo_user",
                    "environment": "development",
                    "created_by": "example_script"
                }
            )
            context_id = context.id
            print(f"   ✓ Context created with ID: {context_id}")

        session = client.sessions.create(
            context={"id": context_id, "mode": "read_write"}
        )
        print(f"   ✓ Session created: {session.id}")
        print(f"   WebSocket URL: {session.connect_url}")
        print(f"   Status: {session.status}")
        print(f"   Container ID: {session.container_id}")
        print("\n   Note: Changes to cookies/storage will be saved when session closes")

        # wait user input
        input("\n   Press Enter to continue...")

        # Close the session (saves context data)
        print("\n   Closing session...")
        session.close()
        print("   ✓ Session closed, context data saved")

    except Exception as e:
        print(f"   ✗ Failed: {e}")
        return

if __name__ == "__main__":
    main()
